### ISSUE TITLE
build error caused by libs/dlib

### ISSUE THREAD

**Issue by gerardobort** [kashimAstro/ofImageNet#2]
Hi @kashimAstro,

I just followed the readme instructions but I get stuck with this error... (this is downloading and extracting `dlib/` into `libs/`).  I tried also linking the `dlib` brew package to the project but get different errors.... I was wondering if you're familiar with this, and if there's a simple workaround.

```
/Users/gbort/openFrameworks/addons/ofImageNet/libs/dlib/all_console.cpp:6:2: error: "This file has been replaced. Instead you should add
      dlib/all/source.cpp to your project"
#error "This file has been replaced.  Instead you should add dlib/all/source.cpp to your project"
 ^
1 error generated.
make[1]: *** [obj/osx/Release/libs/dlib/all_console.o] Error 1
make: *** [Release] Error 2
```

Thanks!

**Comment by gerardobort** [comment]
This issue happens using `dlib-19.4` and `dlib-19.2` on `mac osx`

**Comment by kashimAstro** [comment]
Hi @gerardobort, 

this method to compile dlib with openFrameworks it only tested on linux.

try to use this fork:
https://github.com/kashimAstro/ofxDLib
addons of roymacdonald, I added some examples.

good day

**Comment by gerardobort** [comment]
@kashimAstro thank you for the quick response!
